### ISSUE TITLE
서버 CI/CD 설정

### ISSUE THREAD

**Issue by Zamoca42** [team-3-in/toeic#17]
##  이슈 내용

> 서버 지속 배포 시스템 구축

<br>

##  작업 사항

- [x] GitHub Actions CD 생성
- [x] 배포 시스템 구축
- [x] AWS EC2 설정
- [x] 로드 밸런서 설정
- [x] URI 설정
- [x] PM2 설치
- [x] EC2 인스턴스 내부에서 backend 폴더만 pull 하도록 설정
- [x] github actions 환경변수에 EC2 AWS Secret key 설정
- [x] CI 설정

<br>

## 기타사항

**배포주소: https://api.doit-toeic.xyz**

## PM2 설치

![스크린샷 2024-01-26 오후 6 46 06](https://github.com/team-3-in/toeic/assets/96982072/8d012454-4b4f-4a18-a9c7-61d223d47904)

### 참고 링크
- https://velog.io/@seunghwa17/NestJs-pm2-%EC%A0%81%EC%9A%A9

### 참고링크

- https://velog.io/@ji0ahn/%EC%9B%90%EA%B2%A9-%EB%94%94%EB%A0%89%ED%86%A0%EB%A6%AC%EC%9D%98-%ED%8A%B9%EC%A0%95-%ED%8F%B4%EB%8D%94%EB%A7%8C-pull-push

## CI 설정

feat 브랜치와 backend 폴더에 변경이 있으면 작동하도록 변경

- server-ci.yml

```yml
name: Server CI

on:
  push:
    branches: [feat/*]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: "backend"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm run test:cov

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: "backend"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

```

![스크린샷 2024-01-26 오후 7 44 00](https://github.com/team-3-in/toeic/assets/96982072/0cf1106d-c27d-4f60-a8fa-9ccb0eb4f52d)

<br>
